#!/usr/bin/env bash
set -euo pipefail

R_BIN=${R_BIN:-Rscript}
ONEPASS="scripts/matcher_onepass.R"         # strict: --query は RDS(list(q1,q2)) 前提
FIXQ="scripts/fix_query.R"                  # CLI版
EMIT="scripts/emit/emit_detail.R"           # ← 正しいパスに修正（サブディレクトリ emit/）
MEASURE="scripts/measure_wrap.R"            # 任意

DB1K="data/virtual_db_u100_S1000_seed101.rds"
QUERY_CSV="data/query_profile_seed101.csv"

OUTROOT="output/smoke_$(date +%Y%m%d%H%M%S)"
mkdir -p "$OUTROOT"

run_case () {
  local TAG=$1
  local DB=$2
  local QCSV=$3
  local OUTD=$4

  mkdir -p "$OUTD"
  echo "== RUN: ${TAG} =="

  # A) fix_query（CSV→RDS）
  local QFIX="${OUTD}/query_fixed.rds"
  "$R_BIN" "$FIXQ" --query "$QCSV" --out-rds "$QFIX" --no-audit 1
  if [ ! -s "$QFIX" ]; then echo "[ERR] fix_query did not produce $QFIX"; exit 1; fi
  echo "[OK] fix_query wrote $QFIX"

  # B) onepass（strict）
  "$R_BIN" "$ONEPASS" \
    --db "$DB" \
    --query "$QFIX" \
    --out "$OUTD/scores.csv" \
    --report all \
    --n_cap 1000 \
    --debug 1
  echo "[OK] order: ${TAG}"

  # C) emit_detail（opts_scores.json + scores.csv + out-dir）
  "$R_BIN" "$EMIT" \
    --opt-path "$OUTD/opts_scores.json" \
    --scores-path "$OUTD/scores.csv" \
    --out-dir "$OUTD" \
    --mode raw \
    --any-code 9999
  echo "[OK] raw_detail.csv generated by emit_detail"

  # D) raw 20 抜き出し
  mkdir -p "$OUTD/_raw20"
  cut -d, -f1 "$OUTD/scores.csv" | tail -n +2 | shuf -n 20 > "$OUTD/ids_20.txt"
  while read -r sid; do
    grep "$sid" "$OUTD/raw_detail.csv" > "$OUTD/_raw20/${sid}.csv" || true
  done < "$OUTD/ids_20.txt"
  echo "[OK] emit_detail raw for 20 samples at $OUTD/_raw20"

  # E) 中間削除
  rm -f "$QFIX"

  echo "[OK] ${TAG}"
}

run_case "1k_normal_off" "$DB1K" "$QUERY_CSV" "$OUTROOT/1k_normal_off"
echo "[DONE] smoke(min strict) => $OUTROOT"

# 想定結果:
# - scores.csv: 1000 行（Score 降順）
# - hist.csv  : 44 行（ヘッダ + 0..42 = 43 bin）
# - raw_detail.csv: emit_detail 再構成（Top10 厳格一致・bits 寛容）
# - _raw20/   : 20 サンプルの raw を保存
# - opts_scores.json, time.log（LOAD_* = NA, TOTAL_SEC のみ値；計測は外部化で対応）
